services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  Dvc\ContaoContainerWrapperBundle\Configuration\ContentElementConfiguration:
    public: true

  Dvc\ContaoContainerWrapperBundle\Configuration\ContainerValueBag:
    public: true

  Dvc\ContaoContainerWrapperBundle\Controller\ContentElement\StartWrapperController:

  Dvc\ContaoContainerWrapperBundle\Controller\ContentElement\EndWrapperController:

  Dvc\ContaoContainerWrapperBundle\Widget\Backend\ContainerDataWidget:

  Dvc\ContaoContainerWrapperBundle\Twig\ContainerExtension:

  Dvc\ContaoContainerWrapperBundle\Builder\TemplateBuilder:

  Dvc\ContaoContainerWrapperBundle\Twig\TemplateBuilderExtension:

  Dvc\ContaoContainerWrapperBundle\EventListener\LoadDataContainerListener:
    autowire: true
    autoconfigure: true

  Dvc\ContaoContainerWrapperBundle\EventListener\OnSubmitListener:

  Dvc\ContaoContainerWrapperBundle\EventListener\BackendAssetsListener:
    tags:
      - {
          name: kernel.event_listener,
          event: kernel.request
      }

  Twig\Extension\StringLoaderExtension:
